### PR TITLE
Setting up the attack class.

### PR DESCRIPTION
**Pull request by NoahThrelfall-Holmes**
Using the 'Strategy Pattern' to promote reusability. Pushing now while the code is clean.
Ask anything you need to, let me know if comments would be helpful.

### CODE REVIEW

**Comment by NoahThrelfall-Holmes** [comment]
From 2nd commit:
attack is a locked state. bc of the way movement is done atm you cannot move while attacking (in theory) in practise this is unnoticeable bc the attack state exits as soon as it enters.
If however, in the current system, we made an attack anim and had to wait for the attack to be 'done' the character would be standing still during this time, except for the momentum of the rigidbody. /would not be receiving movement inputs while in the attack state.

**Comment by imreyn** [comment]
Strategy system/State Machine processes look usable to me. We'll need to change some of the state's current functionalities (overwrite the basic rb.velocity movement, remove attack booleans, etc. changing basic functions to final gameplay targets), and see how that may effect the current setup, but as it is now should be workable with minor changes.

**Review by imreyn — COMMENTED** [review]
.

**Review by imreyn — APPROVED** [review]
Strategy system/State Machine processes look usable to me. We'll need to change some of the state's current functionalities (overwrite the basic rb.velocity movement, remove attack booleans, etc. changing basic functions to final gameplay targets), and see how that may effect the current setup, but as it is now should be workable with minor changes.

**Pull request merged**
